// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_widgets
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'MOCK_API_KEY',
    appId: 'MOCK_APP_ID',
    messagingSenderId: 'MOCK_SENDER_ID',
    projectId: 'lockapp-mock',
    authDomain: 'lockapp-mock.firebaseapp.com',
    storageBucket: 'lockapp-mock.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjH8P5pZ-P8d5eF2_V9G1UeyQy3Yn_-hs',
    appId: '1:330397935709:android:7128ff2b87037019ef05b4',
    messagingSenderId: '330397935709',
    projectId: 'lockapp-de964',
    storageBucket: 'lockapp-de964.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ7eOYYYg3pq7juFcgDyNm4ANBrGbGZSc',
    appId: '1:330397935709:ios:07537eafa0d3970fef05b4',
    messagingSenderId: '330397935709',
    projectId: 'lockapp-de964',
    storageBucket: 'lockapp-de964.firebasestorage.app',
    iosBundleId: 'com.aasoft.lockapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'MOCK_API_KEY',
    appId: 'MOCK_APP_ID',
    messagingSenderId: 'MOCK_SENDER_ID',
    projectId: 'lockapp-mock',
    storageBucket: 'lockapp-mock.appspot.com',
    iosBundleId: 'com.example.lockapp',
  );
}